'use client';
import Link from 'next/link';
import {useEffect,useMemo,useRef,useState} from 'react';
import {products} from '../lib/products';
const initialFilters={search:'',type:'',phase:'',power:'',compliance:'',watts:''};
const categories=['On-grid','Hybrid','Microinverter','Off-grid','Solar panels','Storage','All-in-one ESS','Accessories'];
const wattages=[550,555,560,565,570,575,580,605,610,615,620,625,630,635,640];
const notes={local:'Explore the Wekraft range: Deye products and Adani TOPCon modules. DCR: 550–580 Wp and 605–640 Wp. Non-DCR: 625, 630 and 635 Wp. Contact our team for availability.',global:'Explore Deye’s global inverter series, including regional models. Confirm India availability and grid compatibility with our team.',all:'Wekraft products, Adani module series and Deye’s global inverter catalogue. Manufacturer series and Wekraft capacity entries are shown separately.'};
export default function Catalogue(){
 const [filters,setFilters]=useState(initialFilters),[range,setRange]=useState('local'),[page,setPage]=useState(1),[selected,setSelected]=useState(null);
 const dialog=useRef(null),tools=useRef(null);
 useEffect(()=>{const params=new URLSearchParams(window.location.search);if(categories.includes(params.get('type')))setFilters(f=>({...f,type:params.get('type')}));if(['global','all'].includes(params.get('range')))setRange(params.get('range'));},[]);
 useEffect(()=>{if(selected)dialog.current?.showModal();},[selected]);
 const change=(key,value)=>{setFilters(f=>({...f,[key]:value}));setPage(1);};
 const matches=useMemo(()=>products.filter(p=>{
  if(range==='local'&&p.source==='Deye global range')return false;
  if(range==='global'&&p.source!=='Deye global range')return false;
  if(filters.type&&p.type!==filters.type)return false;
  if(filters.phase&&p.phase!==filters.phase)return false;
  if(filters.compliance&&p.compliance!==filters.compliance)return false;
  if(filters.watts&&p.watts!==Number(filters.watts))return false;
  if(filters.power){const [min,max]=filters.power.split('-').map(Number);if(!p.powers.some(v=>v>min&&v<=max))return false;}
  const text=[p.name,p.type,p.phase,p.brand,p.description,...p.specs,p.region,p.compliance||'',p.watts?p.watts+' Wp':'',...p.powers.map(v=>v+' kW')].join(' ').toLowerCase();
  return filters.search.toLowerCase().trim().split(/\s+/).every(t=>text.includes(t));
 }),[filters,range]);
 const pages=Math.max(1,Math.ceil(matches.length/12)),current=Math.min(page,pages);
 const paginate=direction=>{setPage(current+direction);tools.current?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth',block:'start'});};
 const close=()=>dialog.current?.close();
 const select=(key,label,placeholder,options)=><label>{label}<select id={'catalog-'+key} value={filters[key]} onChange={e=>change(key,e.target.value)}><option value="">{placeholder}</option>{options.map(o=>{const [value,text]=Array.isArray(o)?o:[o,o];return <option key={value} value={value}>{text}</option>;})}</select></label>;
 const specs=selected?[['Range',selected.source],['Region',selected.region],['Phase',selected.phase],['Power',selected.watts?selected.watts+' Wp':selected.powers.length?selected.powers.join(' / ')+' kW':''],...(selected.extraSpecs||[]),...selected.specs.filter(s=>s!==selected.phase&&s!==selected.description).map(s=>['Technology',s])].filter(s=>s[1]):[];
 return <><main id="main"><section className="catalog-intro" id="catalogue"><div className="wrap"><div className="eyebrow light">THE WEKRAFT PRODUCT CATALOGUE</div><h1>The right power.<br/><em>For every project.</em></h1><p>Explore Deye inverters, energy storage and Adani DCR and non-DCR TOPCon modules. Find your model, review the details and connect with our team.</p><div className="catalog-tabs" role="group" aria-label="Product range">{[['local','Wekraft range'],['global','Deye global inverter range'],['all','All products']].map(([value,label])=><button key={value} aria-pressed={range===value} onClick={()=>{setRange(value);setPage(1);}}>{label}</button>)}</div></div></section>
 <section className="wrap catalog-main"><div className="catalog-tools" ref={tools}><label className="search-field">Search models or specifications<input id="catalog-search" type="search" placeholder="Try 40 kW, hybrid, TOPCon or SUN…" value={filters.search} onChange={e=>change('search',e.target.value)}/></label>
 {select('type','Category','All categories',categories)}{select('phase','Phase','All phases',['Single phase','Three phase','Split phase'])}{select('power','Power','All capacities',[['0-6','Up to 6 kW'],['6-20','Over 6–20 kW'],['20-60','Over 20–60 kW'],['60-9999','Over 60 kW']])}{select('compliance','Module class','DCR & non-DCR',['DCR','Non-DCR'])}{select('watts','Module wattage','All module wattages',wattages.map(w=>[String(w),w+' Wp']))}
 </div><div className="catalog-results-head"><p id="result-count" aria-live="polite">{matches.length} products and series{filters.type?' · '+filters.type:''}</p><button className="clear-filters" onClick={()=>{setFilters(initialFilters);setPage(1);}}>Reset filters</button></div><p className="range-note">{notes[range]}</p>
 <div id="catalog-grid" className="catalog-grid">{matches.slice((current-1)*12,current*12).map(p=><article key={p.id} className="model-card">{p.image?<div className="model-image"><img src={p.image} alt={p.name} loading="lazy" width="300" height="200"/></div>:<div className="model-cover"><span>{p.type.toUpperCase()}</span><strong>{p.watts?p.watts+' Wp':p.source==='Wekraft range'&&p.powers.length?p.powers[0]+' kW':p.brand==='Adani Solar'?'Adani Solar':p.type}</strong></div>}<div className="model-body"><span className="model-brand">{p.brand.toUpperCase()}</span><h3>{p.name}</h3>{p.description&&<p className="model-description">{p.description}</p>}<div className="model-tags">{[p.type,p.compliance,p.phase,p.source==='Deye global range'?p.region:''].filter(Boolean).map((t,i)=><span key={i}>{t}</span>)}</div><button className="text-button" onClick={()=>setSelected(p)}>View model details<span>+</span></button><p className="model-origin">{p.source}</p></div></article>)}{!matches.length&&<div className="empty-results"><h3>No matching products</h3><p>Try another model name or reset the filters.</p></div>}</div>
 <div className="pagination"><button disabled={current===1} onClick={()=>paginate(-1)}>Previous</button><span>Page {current} of {pages}</span><button disabled={current===pages} onClick={()=>paginate(1)}>Next</button></div><div className="catalog-help"><div><h2>Found your next solar solution?</h2><p>Our team can confirm model availability and help with product selection.</p></div><Link className="button" href="/contact">Contact Wekraft</Link></div><div className="catalog-sources"><span>Manufacturer resources</span><a href="https://www.deyeinverter.com/" target="_blank" rel="noopener noreferrer">Deye official catalogue</a><a href="https://www.adanisolar.com/" target="_blank" rel="noopener noreferrer">Adani Solar official catalogue</a></div></section></main>
 <dialog id="catalog-dialog" aria-labelledby="detail-name" ref={dialog} onClose={()=>setSelected(null)} onClick={e=>{if(e.target===dialog.current){const r=dialog.current.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close();}}}><button className="close" aria-label="Close product details" onClick={close}>×</button>{selected&&<><div className="eyebrow">{selected.brand} · {selected.type}</div><h2 id="detail-name">{selected.name}</h2><p>{selected.description||selected.type+' inverter'}</p><dl>{specs.map(([label,value],i)=><div key={i}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="dialog-note">{selected.source==='Deye global range'?'This is a manufacturer catalogue series. Confirm regional compatibility, local availability and exact specifications with Wekraft before selecting a model.':'Contact Wekraft for model availability, exact specifications and product selection.'}</p><div className="detail-actions"><a className="button" href={'mailto:anup.shetty@wekraft.co.in?subject='+encodeURIComponent('Product enquiry: '+selected.name)+'&body='+encodeURIComponent('Hello Wekraft,\n\nPlease share availability and specifications for '+selected.name+'.')}>Enquire about this model</a>{selected.url&&<a className="source-button" href={selected.url} target="_blank" rel="noopener noreferrer">{selected.url.endsWith('.pdf')?'View product datasheet':'Manufacturer details'}</a>}</div></>}</dialog></>;
}
